import { Router } from "express";import pool from "../db/index.js";import { authRequired,adminRequired } from "../middleware/auth.js";
const router = Router();router.use(authRequired);
const J=`FROM assets a LEFT JOIN packages p ON a.package_id=p.id LEFT JOIN fcps f ON a.fcp_id=f.id LEFT JOIN utcs u ON a.utc_id=u.id LEFT JOIN increments inc ON a.increment_id=inc.id LEFT JOIN warehouse_locations awl ON a.warehouse_location_id=awl.id LEFT JOIN warehouse_locations fwl ON f.warehouse_location_id=fwl.id`;
const C=`a.*,p.name as package_name,p.type as package_type,f.name as fcp_name,f.status as fcp_status,u.name as utc_name,inc.name as increment_name,inc.inc_number,COALESCE(awl.label,fwl.label) as location_label,COALESCE(a.warehouse_location_id,f.warehouse_location_id) as effective_location_id`;

router.get("/meta/stats",async(_,r)=>{try{r.json((await pool.query(`SELECT COUNT(*)as total,COUNT(*)FILTER(WHERE status='Deployed')as deployed,COUNT(*)FILTER(WHERE status='Ready to Deploy')as ready,COUNT(*)FILTER(WHERE status='Pending')as pending,COUNT(*)FILTER(WHERE status='In Maintenance')as maintenance FROM assets`)).rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});
router.get("/meta/activity",async(_,r)=>{try{r.json((await pool.query(`SELECT h.*,a.asset_tag,a.name as asset_name FROM asset_history h JOIN assets a ON h.asset_id=a.id ORDER BY h.created_at DESC LIMIT 20`)).rows);}catch(e){r.status(500).json({error:"Failed"});}});
router.get("/meta/filters",async(_,r)=>{try{const q=async n=>(await pool.query("SELECT value FROM dropdown_options WHERE dropdown_name=$1 AND is_active=true ORDER BY display_order",[n])).rows.map(x=>x.value);const locs=(await pool.query("SELECT id,label FROM warehouse_locations ORDER BY row_label,col_number")).rows;r.json({categories:await q("category"),statuses:await q("status"),locations:locs});}catch(e){r.status(500).json({error:"Failed"});}});
router.get("/meta/dropdowns",async(_,r)=>{try{const q=async n=>(await pool.query("SELECT value FROM dropdown_options WHERE dropdown_name=$1 AND is_active=true ORDER BY display_order",[n])).rows.map(x=>x.value);r.json({categories:await q("category"),statuses:await q("status"),models:await q("model"),component_statuses:await q("component_status")});}catch(e){r.status(500).json({error:"Failed"});}});

router.get("/lookup/:query",async(req,r)=>{try{const q=req.params.query,res=await pool.query(`SELECT ${C} ${J} WHERE a.asset_tag=$1 OR a.serial=$1 OR a.id=$1`,[q]);if(!res.rows.length)return r.status(404).json({error:"Not found"});const id=res.rows[0].id;const[h,comps,cf]=await Promise.all([pool.query("SELECT * FROM asset_history WHERE asset_id=$1 ORDER BY created_at DESC",[id]),pool.query("SELECT * FROM asset_components WHERE asset_id=$1 ORDER BY category,name",[id]),pool.query("SELECT cfv.*,cf.name,cf.field_key,cf.field_type FROM custom_field_values cfv JOIN custom_fields cf ON cfv.field_id=cf.id WHERE cfv.asset_id=$1",[id])]);r.json({...res.rows[0],history:h.rows,components:comps.rows,custom_fields:cf.rows});}catch(e){r.status(500).json({error:"Failed"});}});

router.get("/",async(req,r)=>{try{const{search,category,status,fcp_id,package_id,increment_id,location_id,component,limit=500,offset=0}=req.query;let w=[],p=[],i=1,ej="";
  if(search){w.push(`(a.name ILIKE $${i} OR a.asset_tag ILIKE $${i} OR a.serial ILIKE $${i} OR a.model ILIKE $${i})`);p.push(`%${search}%`);i++;}
  if(category&&category!=="All"){w.push(`a.category=$${i}`);p.push(category);i++;}if(status&&status!=="All"){w.push(`a.status=$${i}`);p.push(status);i++;}
  if(fcp_id&&fcp_id!=="All"){w.push(`a.fcp_id=$${i}`);p.push(fcp_id);i++;}if(package_id&&package_id!=="All"){w.push(`a.package_id=$${i}`);p.push(package_id);i++;}
  if(increment_id){w.push(`a.increment_id=$${i}`);p.push(increment_id);i++;}
  if(location_id&&location_id!=="All"){w.push(`COALESCE(a.warehouse_location_id,f.warehouse_location_id)=$${i}`);p.push(location_id);i++;}
  if(component){ej=` LEFT JOIN asset_components ac ON ac.asset_id=a.id`;w.push(`ac.name ILIKE $${i}`);p.push(`%${component}%`);i++;}
  const wc=w.length?`WHERE ${w.join(" AND ")}`:"";
  const cnt=await pool.query(`SELECT COUNT(DISTINCT a.id) ${J}${ej} ${wc}`,p);
  const res=await pool.query(`SELECT DISTINCT ON (a.created_at,a.id) ${C} ${J}${ej} ${wc} ORDER BY a.created_at DESC,a.id LIMIT $${i} OFFSET $${i+1}`,[...p,parseInt(limit),parseInt(offset)]);
  r.json({assets:res.rows,total:parseInt(cnt.rows[0].count)});}catch(e){console.error(e);r.status(500).json({error:"Failed"});}});

router.get("/:id",async(req,r)=>{try{const res=await pool.query(`SELECT ${C} ${J} WHERE a.id=$1`,[req.params.id]);if(!res.rows.length)return r.status(404).json({error:"Not found"});const id=req.params.id;const[h,comps,cf,docs]=await Promise.all([pool.query("SELECT * FROM asset_history WHERE asset_id=$1 ORDER BY created_at DESC",[id]),pool.query("SELECT * FROM asset_components WHERE asset_id=$1 ORDER BY category,name",[id]),pool.query("SELECT cfv.*,cf.name,cf.field_key,cf.field_type FROM custom_field_values cfv JOIN custom_fields cf ON cfv.field_id=cf.id WHERE cfv.asset_id=$1",[id]),pool.query("SELECT id,original_name,file_size,mime_type,uploaded_by,created_at FROM documents WHERE asset_id=$1 ORDER BY created_at DESC",[id])]);r.json({...res.rows[0],history:h.rows,components:comps.rows,custom_fields:cf.rows,documents:docs.rows});}catch(e){r.status(500).json({error:"Failed"});}});

router.post("/",async(req,r)=>{try{const{assetTag,serial,name,model,category,status,packageId,fcpId,utcId,incrementId,warehouseLocationId,notes}=req.body;if(!assetTag||!serial||!name)return r.status(400).json({error:"Required"});const id=`asset-${Date.now()}-${Math.random().toString(36).substr(2,5)}`;let locId=warehouseLocationId||null;if(!locId&&fcpId){const fl=await pool.query("SELECT warehouse_location_id FROM fcps WHERE id=$1",[fcpId]);if(fl.rows.length)locId=fl.rows[0].warehouse_location_id;}await pool.query("INSERT INTO assets (id,asset_tag,serial,name,model,category,status,package_id,fcp_id,utc_id,increment_id,warehouse_location_id,notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)",[id,assetTag,serial,name,model||"",category||"Uncategorized",status||"Ready to Deploy",packageId||null,fcpId||null,utcId||null,incrementId||null,locId,notes||""]);await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[id,"Created",req.user.displayName,"Asset added"]);r.status(201).json((await pool.query(`SELECT ${C} ${J} WHERE a.id=$1`,[id])).rows[0]);}catch(e){e.code==="23505"?r.status(409).json({error:"Duplicate"}):r.status(500).json({error:"Failed"});}});
router.put("/:id",async(req,r)=>{try{const b=req.body;const sets=[];const vals=[req.params.id];let i=2;
  const add=(col,val)=>{if(val!==undefined){sets.push(`${col}=$${i}`);vals.push(val);i++;}};
  add("asset_tag",b.assetTag);add("serial",b.serial);add("name",b.name);add("model",b.model);add("category",b.category);add("status",b.status);add("notes",b.notes);
  if(b.packageId!==undefined){add("package_id",b.packageId||null);}if(b.fcpId!==undefined){add("fcp_id",b.fcpId||null);}if(b.utcId!==undefined){add("utc_id",b.utcId||null);}if(b.incrementId!==undefined){add("increment_id",b.incrementId||null);}if(b.warehouseLocationId!==undefined){add("warehouse_location_id",b.warehouseLocationId||null);}
  if(sets.length)await pool.query(`UPDATE assets SET ${sets.join(",")} WHERE id=$1`,vals);
  await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[req.params.id,"Updated",req.user.displayName,"Updated"]);r.json((await pool.query(`SELECT ${C} ${J} WHERE a.id=$1`,[req.params.id])).rows[0]);}catch(e){console.error(e);r.status(500).json({error:"Failed"});}});
router.delete("/:id",adminRequired,async(req,r)=>{try{await pool.query("DELETE FROM assets WHERE id=$1",[req.params.id]);r.json({deleted:true});}catch(e){r.status(500).json({error:"Failed"});}});
router.post("/:id/checkin",async(req,r)=>{try{await pool.query("UPDATE assets SET status='Ready to Deploy' WHERE id=$1",[req.params.id]);await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[req.params.id,"Checked In",req.user.displayName,"Checked in"]);r.json((await pool.query("SELECT * FROM assets WHERE id=$1",[req.params.id])).rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});
router.post("/:id/checkout",async(req,r)=>{try{const{assignTo}=req.body;await pool.query("UPDATE assets SET status='Deployed' WHERE id=$1",[req.params.id]);await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[req.params.id,"Checked Out",req.user.displayName,`To ${assignTo||req.user.displayName}`]);r.json((await pool.query("SELECT * FROM assets WHERE id=$1",[req.params.id])).rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});
// Bulk
router.post("/bulk/status",async(req,r)=>{try{const{assetIds,status}=req.body;for(const id of assetIds){await pool.query("UPDATE assets SET status=$2 WHERE id=$1",[id,status]);await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[id,"Bulk Status",req.user.displayName,`→ ${status}`]);}r.json({updated:assetIds.length});}catch(e){r.status(500).json({error:"Failed"});}});
router.post("/bulk/delete",adminRequired,async(req,r)=>{try{for(const id of req.body.assetIds)await pool.query("DELETE FROM assets WHERE id=$1",[id]);r.json({deleted:req.body.assetIds.length});}catch(e){r.status(500).json({error:"Failed"});}});
// Components
router.get("/:id/components",async(req,r)=>{try{r.json((await pool.query("SELECT * FROM asset_components WHERE asset_id=$1 ORDER BY category,name",[req.params.id])).rows);}catch(e){r.status(500).json({error:"Failed"});}});
router.post("/:id/components",async(req,r)=>{try{const{name,quantity,category,serial,status,notes}=req.body;const res=await pool.query("INSERT INTO asset_components (asset_id,name,quantity,category,serial,status,notes) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *",[req.params.id,name,quantity||1,category||"",serial||"",status||"Good",notes||""]);await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[req.params.id,"Component Added",req.user.displayName,`+${quantity||1}x ${name}`]);r.status(201).json(res.rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});
router.put("/:aid/components/:cid",async(req,r)=>{try{const{name,quantity,category,serial,status,notes}=req.body;const old=(await pool.query("SELECT * FROM asset_components WHERE id=$1",[req.params.cid])).rows[0];await pool.query("UPDATE asset_components SET name=COALESCE($2,name),quantity=COALESCE($3,quantity),category=COALESCE($4,category),serial=COALESCE($5,serial),status=COALESCE($6,status),notes=COALESCE($7,notes),updated_at=NOW() WHERE id=$1",[req.params.cid,name,quantity,category,serial,status,notes]);if(old&&(quantity!==undefined||status))await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[req.params.aid,"Component Updated",req.user.displayName,`${old.name} updated`]);r.json((await pool.query("SELECT * FROM asset_components WHERE id=$1",[req.params.cid])).rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});
router.delete("/:aid/components/:cid",async(req,r)=>{try{const old=(await pool.query("SELECT name,quantity FROM asset_components WHERE id=$1",[req.params.cid])).rows[0];await pool.query("DELETE FROM asset_components WHERE id=$1",[req.params.cid]);if(old)await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[req.params.aid,"Component Removed",req.user.displayName,`-${old.quantity}x ${old.name}`]);r.json({deleted:true});}catch(e){r.status(500).json({error:"Failed"});}});
// Custom field values
router.get("/:id/custom-fields",async(req,r)=>{try{const vals=await pool.query("SELECT cfv.*,cf.name,cf.field_key,cf.field_type,cf.options FROM custom_field_values cfv JOIN custom_fields cf ON cfv.field_id=cf.id WHERE cfv.asset_id=$1",[req.params.id]);const all=await pool.query("SELECT * FROM custom_fields WHERE is_active=true ORDER BY display_order");r.json({values:vals.rows,fields:all.rows});}catch(e){r.status(500).json({error:"Failed"});}});
router.put("/:id/custom-fields",async(req,r)=>{try{for(const{field_id,value}of req.body.fields)await pool.query("INSERT INTO custom_field_values (asset_id,field_id,value) VALUES ($1,$2,$3) ON CONFLICT (asset_id,field_id) DO UPDATE SET value=$3",[req.params.id,field_id,value||""]);await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[req.params.id,"Custom Fields Updated",req.user.displayName,"Fields updated"]);r.json({success:true});}catch(e){r.status(500).json({error:"Failed"});}});
export default router;
