import { Router } from "express";import bcrypt from "bcryptjs";import pool from "../db/index.js";import { generateToken,authRequired,adminRequired } from "../middleware/auth.js";
const router = Router();
router.post("/register",async(req,r)=>{try{const{username,password,displayName}=req.body;if(!username||!password||!displayName)return r.status(400).json({error:"All fields required"});if(password.length<8)return r.status(400).json({error:"8+ chars"});const ex=await pool.query("SELECT id FROM users WHERE username=$1",[username.toLowerCase()]);if(ex.rows.length)return r.status(409).json({error:"Taken"});const cnt=await pool.query("SELECT COUNT(*) FROM users");const isFirst=parseInt(cnt.rows[0].count)===0;const hash=await bcrypt.hash(password,12);const res=await pool.query("INSERT INTO users (username,display_name,password_hash,role) VALUES ($1,$2,$3,$4) RETURNING id,username,display_name,role",[username.toLowerCase(),displayName,hash,isFirst?"admin":"user"]);const u=res.rows[0];r.status(201).json({token:generateToken(u),user:{id:u.id,username:u.username,displayName:u.display_name,role:u.role}});}catch(e){r.status(500).json({error:"Failed"});}});
router.post("/login",async(req,r)=>{try{const{username,password}=req.body;if(!username||!password)return r.status(400).json({error:"Required"});const res=await pool.query("SELECT id,username,display_name,password_hash,role FROM users WHERE username=$1",[username.toLowerCase()]);if(!res.rows.length)return r.status(401).json({error:"Invalid"});const u=res.rows[0];if(!(await bcrypt.compare(password,u.password_hash)))return r.status(401).json({error:"Invalid"});r.json({token:generateToken(u),user:{id:u.id,username:u.username,displayName:u.display_name,role:u.role}});}catch(e){r.status(500).json({error:"Failed"});}});
router.get("/me",authRequired,async(req,r)=>{try{const res=await pool.query("SELECT id,username,display_name,role FROM users WHERE id=$1",[req.user.id]);if(!res.rows.length)return r.status(404).json({error:"Not found"});const u=res.rows[0];r.json({id:u.id,username:u.username,displayName:u.display_name,role:u.role});}catch(e){r.status(500).json({error:"Failed"});}});
router.get("/users",authRequired,adminRequired,async(_,r)=>{try{r.json((await pool.query("SELECT id,username,display_name,role,created_at FROM users ORDER BY created_at")).rows);}catch(e){r.status(500).json({error:"Failed"});}});
router.put("/users/:id",authRequired,adminRequired,async(req,r)=>{try{const{role,displayName}=req.body;if(role)await pool.query("UPDATE users SET role=$2 WHERE id=$1",[req.params.id,role]);if(displayName)await pool.query("UPDATE users SET display_name=$2 WHERE id=$1",[req.params.id,displayName]);r.json((await pool.query("SELECT id,username,display_name,role FROM users WHERE id=$1",[req.params.id])).rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});
router.delete("/users/:id",authRequired,adminRequired,async(req,r)=>{try{if(parseInt(req.params.id)===req.user.id)return r.status(400).json({error:"Cannot delete yourself"});await pool.query("DELETE FROM users WHERE id=$1",[req.params.id]);r.json({deleted:true});}catch(e){r.status(500).json({error:"Failed"});}});
export default router;
