import { Router } from "express";import pool from "../db/index.js";import { authRequired } from "../middleware/auth.js";
const router = Router();router.use(authRequired);
router.get("/utcs",async(_,r)=>{try{r.json((await pool.query("SELECT * FROM utcs ORDER BY name")).rows);}catch(e){r.status(500).json({error:"Failed"});}});
router.post("/utcs",async(req,r)=>{try{const{id,name,description}=req.body;const uid=id||`utc-${Date.now()}`;await pool.query("INSERT INTO utcs (id,name,description) VALUES ($1,$2,$3)",[uid,name,description||""]);r.status(201).json((await pool.query("SELECT * FROM utcs WHERE id=$1",[uid])).rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});
router.get("/fcps",async(_,r)=>{try{r.json((await pool.query(`SELECT f.*,u.name as utc_name,wl.label as warehouse_label,(SELECT COUNT(*)FROM increments i WHERE i.fcp_id=f.id)as inc_count,(SELECT COUNT(*)FROM assets a WHERE a.fcp_id=f.id)as asset_count,(SELECT COUNT(*)FROM assets a WHERE a.fcp_id=f.id AND a.status='Deployed')as deployed_count FROM fcps f LEFT JOIN utcs u ON f.utc_id=u.id LEFT JOIN warehouse_locations wl ON f.warehouse_location_id=wl.id ORDER BY f.name`)).rows);}catch(e){r.status(500).json({error:"Failed"});}});
router.post("/fcps",async(req,r)=>{try{const{id,name,utcId,status}=req.body;const fid=id||`fcp-${Date.now()}`;await pool.query("INSERT INTO fcps (id,name,utc_id,status) VALUES ($1,$2,$3,$4)",[fid,name,utcId,status||"Ready to Deploy"]);r.status(201).json((await pool.query("SELECT * FROM fcps WHERE id=$1",[fid])).rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});
router.put("/fcps/:id",async(req,r)=>{try{const{status,warehouse_location_id}=req.body;if(status)await pool.query("UPDATE fcps SET status=$2 WHERE id=$1",[req.params.id,status]);if(warehouse_location_id!==undefined)await pool.query("UPDATE fcps SET warehouse_location_id=$2 WHERE id=$1",[req.params.id,warehouse_location_id||null]);r.json((await pool.query("SELECT * FROM fcps WHERE id=$1",[req.params.id])).rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});
router.post("/fcps/:id/cascade-status",async(req,r)=>{try{const{status}=req.body;await pool.query("UPDATE fcps SET status=$2 WHERE id=$1",[req.params.id,status]);const assets=await pool.query("SELECT id FROM assets WHERE fcp_id=$1",[req.params.id]);for(const a of assets.rows){await pool.query("UPDATE assets SET status=$2 WHERE id=$1",[a.id,status]);await pool.query("INSERT INTO asset_history (asset_id,action,user_name,details) VALUES ($1,$2,$3,$4)",[a.id,"FCP Cascade",req.user.displayName,`→ ${status}`]);}r.json({updated:assets.rows.length});}catch(e){r.status(500).json({error:"Failed"});}});
router.get("/packages",async(req,r)=>{try{const{fcp_id}=req.query;let q="SELECT p.*,f.name as fcp_name,(SELECT COUNT(*)FROM assets a WHERE a.package_id=p.id)as asset_count FROM packages p LEFT JOIN fcps f ON p.fcp_id=f.id";const p=[];if(fcp_id){q+=" WHERE p.fcp_id=$1";p.push(fcp_id);}q+=" ORDER BY p.name";r.json((await pool.query(q,p)).rows);}catch(e){r.status(500).json({error:"Failed"});}});

// Increments
router.get("/increments",async(req,r)=>{try{const{fcp_id}=req.query;let q="SELECT i.*,f.name as fcp_name,(SELECT COUNT(*)FROM assets a WHERE a.increment_id=i.id)as asset_count FROM increments i LEFT JOIN fcps f ON i.fcp_id=f.id";const p=[];if(fcp_id){q+=" WHERE i.fcp_id=$1";p.push(fcp_id);}q+=" ORDER BY i.fcp_id,i.inc_number";r.json((await pool.query(q,p)).rows);}catch(e){r.status(500).json({error:"Failed"});}});
router.get("/increments/:id",async(req,r)=>{try{const inc=(await pool.query("SELECT i.*,f.name as fcp_name FROM increments i LEFT JOIN fcps f ON i.fcp_id=f.id WHERE i.id=$1",[req.params.id])).rows[0];if(!inc)return r.status(404).json({error:"Not found"});const assets=(await pool.query("SELECT a.*,p.name as package_name FROM assets a LEFT JOIN packages p ON a.package_id=p.id WHERE a.increment_id=$1 ORDER BY a.asset_tag",[req.params.id])).rows;const reqs=(await pool.query("SELECT * FROM increment_requirements WHERE increment_id=$1 ORDER BY category,item_name",[req.params.id])).rows;const docs=(await pool.query("SELECT id,original_name,file_size,mime_type,uploaded_by,created_at FROM documents WHERE increment_id=$1 ORDER BY created_at DESC",[req.params.id])).rows;
  // Calculate actual vs required
  const actualMap={};for(const a of assets)actualMap[a.category]=(actualMap[a.category]||0)+1;
  // Also count components
  const compRes=await pool.query("SELECT ac.name,SUM(ac.quantity)::int as total FROM asset_components ac JOIN assets a ON ac.asset_id=a.id WHERE a.increment_id=$1 GROUP BY ac.name",[req.params.id]);
  const compMap={};for(const c of compRes.rows)compMap[c.name]=c.total;
  const comparison=reqs.map(rq=>({...rq,actual:actualMap[rq.category]||compMap[rq.item_name]||0,deficit:rq.required_qty-(actualMap[rq.category]||compMap[rq.item_name]||0),total_cost:rq.required_qty*parseFloat(rq.unit_cost)}));
  r.json({...inc,assets,requirements:reqs,comparison,documents:docs,total_required_cost:comparison.reduce((s,c)=>s+c.total_cost,0),total_deficit_cost:comparison.filter(c=>c.deficit>0).reduce((s,c)=>s+c.deficit*parseFloat(c.unit_cost),0)});}catch(e){console.error(e);r.status(500).json({error:"Failed"});}});
router.put("/increments/:id",async(req,r)=>{try{const{fcp_id,notes}=req.body;if(fcp_id)await pool.query("UPDATE increments SET fcp_id=$2 WHERE id=$1",[req.params.id,fcp_id]);if(notes!==undefined)await pool.query("UPDATE increments SET notes=$2 WHERE id=$1",[req.params.id,notes]);// Also move assets if fcp changed
  if(fcp_id){await pool.query("UPDATE assets SET fcp_id=$2 WHERE increment_id=$1",[req.params.id,fcp_id]);}r.json((await pool.query("SELECT * FROM increments WHERE id=$1",[req.params.id])).rows[0]);}catch(e){r.status(500).json({error:"Failed"});}});

// Warehouse
router.get("/warehouse",async(_,r)=>{try{const locs=(await pool.query("SELECT * FROM warehouse_locations ORDER BY row_label,col_number")).rows;const fcps=(await pool.query(`SELECT f.*,wl.label as warehouse_label,(SELECT COUNT(*)FROM increments i WHERE i.fcp_id=f.id)as inc_count,(SELECT COUNT(*)FROM assets a WHERE a.fcp_id=f.id)as asset_count FROM fcps f LEFT JOIN warehouse_locations wl ON f.warehouse_location_id=wl.id ORDER BY f.name`)).rows;const incs=(await pool.query("SELECT i.*,(SELECT COUNT(*)FROM assets a WHERE a.increment_id=i.id)as asset_count FROM increments i ORDER BY i.fcp_id,i.inc_number")).rows;r.json({locations:locs,fcps,increments:incs});}catch(e){r.status(500).json({error:"Failed"});}});
router.put("/warehouse/move-fcp",async(req,r)=>{try{const{fcpId,locationId}=req.body;await pool.query("UPDATE fcps SET warehouse_location_id=$2 WHERE id=$1",[fcpId,locationId||null]);await pool.query("UPDATE assets SET warehouse_location_id=$2 WHERE fcp_id=$1",[fcpId,locationId||null]);r.json({success:true});}catch(e){r.status(500).json({error:"Failed"});}});
router.put("/warehouse/move-inc",async(req,r)=>{try{const{incrementId,targetFcpId}=req.body;await pool.query("UPDATE increments SET fcp_id=$2 WHERE id=$1",[incrementId,targetFcpId]);const fl=await pool.query("SELECT warehouse_location_id FROM fcps WHERE id=$1",[targetFcpId]);const locId=fl.rows[0]?.warehouse_location_id||null;await pool.query("UPDATE assets SET fcp_id=$2,warehouse_location_id=$3 WHERE increment_id=$1",[incrementId,targetFcpId,locId]);r.json({success:true});}catch(e){r.status(500).json({error:"Failed"});}});

// Tree (updated with increments)
router.get("/tree",async(_,r)=>{try{const[utcs,fcps,incs,assets]=await Promise.all([pool.query("SELECT * FROM utcs ORDER BY name"),pool.query("SELECT f.*,wl.label as warehouse_label FROM fcps f LEFT JOIN warehouse_locations wl ON f.warehouse_location_id=wl.id ORDER BY f.name"),pool.query("SELECT i.*,(SELECT COUNT(*)FROM assets WHERE increment_id=i.id)as asset_count FROM increments i ORDER BY i.inc_number"),pool.query("SELECT id,asset_tag,name,model,status,category,fcp_id,increment_id FROM assets ORDER BY asset_tag")]);r.json(utcs.rows.map(u=>({...u,fcps:fcps.rows.filter(f=>f.utc_id===u.id).map(f=>({...f,increments:incs.rows.filter(i=>i.fcp_id===f.id).map(i=>({...i,assets:assets.rows.filter(a=>a.increment_id===i.id)}))}))})));}catch(e){r.status(500).json({error:"Failed"});}});
export default router;
