const TK="cbcmd_token",UK="cbcmd_user";
export function getToken(){return localStorage.getItem(TK);}
export function getUser(){try{return JSON.parse(localStorage.getItem(UK));}catch{return null;}}
export function setAuth(t,u){localStorage.setItem(TK,t);localStorage.setItem(UK,JSON.stringify(u));}
export function clearAuth(){localStorage.removeItem(TK);localStorage.removeItem(UK);}
let onErr=null;export function setAuthErrorHandler(fn){onErr=fn;}
async function req(path,opts={}){const token=getToken(),h={...opts.headers};if(token)h["Authorization"]=`Bearer ${token}`;if(!(opts.body instanceof FormData))h["Content-Type"]="application/json";const res=await fetch(`/api${path}`,{...opts,headers:h});if(res.status===401){clearAuth();if(onErr)onErr();throw new Error("Auth required");}if(!res.ok){const b=await res.json().catch(()=>({}));throw new Error(b.error||`Failed (${res.status})`);}const ct=res.headers.get("content-type")||"";return(ct.includes("spreadsheet")||ct.includes("octet-stream"))?res.blob():res.json();}
export const api={
  login:(u,p)=>req("/auth/login",{method:"POST",body:JSON.stringify({username:u,password:p})}),
  register:(u,p,d)=>req("/auth/register",{method:"POST",body:JSON.stringify({username:u,password:p,displayName:d})}),
  me:()=>req("/auth/me"),
  getAssets:(p={})=>{const q=new URLSearchParams(p).toString();return req(`/assets${q?"?"+q:""}`);},
  getAsset:id=>req(`/assets/${id}`),lookupAsset:q=>req(`/assets/lookup/${encodeURIComponent(q)}`),
  createAsset:d=>req("/assets",{method:"POST",body:JSON.stringify(d)}),
  updateAsset:(id,d)=>req(`/assets/${id}`,{method:"PUT",body:JSON.stringify(d)}),
  deleteAsset:id=>req(`/assets/${id}`,{method:"DELETE"}),
  checkinAsset:id=>req(`/assets/${id}/checkin`,{method:"POST"}),
  checkoutAsset:(id,a)=>req(`/assets/${id}/checkout`,{method:"POST",body:JSON.stringify({assignTo:a})}),
  getStats:()=>req("/assets/meta/stats"),getActivity:()=>req("/assets/meta/activity"),
  getFilters:()=>req("/assets/meta/filters"),getDropdowns:()=>req("/assets/meta/dropdowns"),
  bulkStatus:(ids,st)=>req("/assets/bulk/status",{method:"POST",body:JSON.stringify({assetIds:ids,status:st})}),
  bulkDelete:ids=>req("/assets/bulk/delete",{method:"POST",body:JSON.stringify({assetIds:ids})}),
  getComponents:id=>req(`/assets/${id}/components`),
  addComponent:(id,d)=>req(`/assets/${id}/components`,{method:"POST",body:JSON.stringify(d)}),
  updateComponent:(aid,cid,d)=>req(`/assets/${aid}/components/${cid}`,{method:"PUT",body:JSON.stringify(d)}),
  deleteComponent:(aid,cid)=>req(`/assets/${aid}/components/${cid}`,{method:"DELETE"}),
  getCustomFieldValues:id=>req(`/assets/${id}/custom-fields`),
  updateCustomFieldValues:(id,f)=>req(`/assets/${id}/custom-fields`,{method:"PUT",body:JSON.stringify({fields:f})}),
  getCustomFields:()=>req("/custom-fields"),
  getTree:()=>req("/hierarchy/tree"),getUtcs:()=>req("/hierarchy/utcs"),getFcps:()=>req("/hierarchy/fcps"),
  getPackages:fid=>req(`/hierarchy/packages${fid?"?fcp_id="+fid:""}`),
  updateFcpStatus:(id,st)=>req(`/hierarchy/fcps/${id}`,{method:"PUT",body:JSON.stringify({status:st})}),
  cascadeFcpStatus:(id,st)=>req(`/hierarchy/fcps/${id}/cascade-status`,{method:"POST",body:JSON.stringify({status:st})}),
  moveFcp:(id,locId)=>req("/hierarchy/warehouse/move-fcp",{method:"PUT",body:JSON.stringify({fcpId:id,locationId:locId})}),
  moveInc:(incId,fcpId)=>req("/hierarchy/warehouse/move-inc",{method:"PUT",body:JSON.stringify({incrementId:incId,targetFcpId:fcpId})}),
  getIncrements:fid=>req(`/hierarchy/increments${fid?"?fcp_id="+fid:""}`),
  getIncrement:id=>req(`/hierarchy/increments/${id}`),
  updateIncrement:(id,d)=>req(`/hierarchy/increments/${id}`,{method:"PUT",body:JSON.stringify(d)}),
  getWarehouse:()=>req("/hierarchy/warehouse"),
  importFile:(file,pkgId,incId)=>{const f=new FormData();f.append("file",file);if(pkgId)f.append("packageId",pkgId);if(incId)f.append("incrementId",incId);return req("/data/import",{method:"POST",body:f});},
  uploadDocument:(file,assetId,incId)=>{const f=new FormData();f.append("file",file);if(assetId)f.append("asset_id",assetId);if(incId)f.append("increment_id",incId);return req("/documents/upload",{method:"POST",body:f});},
  getDocuments:(assetId,incId)=>{const p=new URLSearchParams();if(assetId)p.set("asset_id",assetId);if(incId)p.set("increment_id",incId);return req(`/documents/list?${p}`);},
  deleteDocument:id=>req(`/documents/${id}`,{method:"DELETE"}),
  getPublicSettings:()=>req("/settings/public"),getEnabledModules:()=>req("/modules/enabled"),
  getSettings:()=>req("/admin/settings"),updateSettings:s=>req("/admin/settings",{method:"PUT",body:JSON.stringify({settings:s})}),
  getDropdownsAdmin:()=>req("/admin/dropdowns"),addDropdownOption:(n,v)=>req("/admin/dropdowns",{method:"POST",body:JSON.stringify({dropdown_name:n,value:v})}),
  updateDropdownOption:(id,d)=>req(`/admin/dropdowns/${id}`,{method:"PUT",body:JSON.stringify(d)}),deleteDropdownOption:id=>req(`/admin/dropdowns/${id}`,{method:"DELETE"}),
  getModules:()=>req("/admin/modules"),updateModule:(id,d)=>req(`/admin/modules/${id}`,{method:"PUT",body:JSON.stringify(d)}),
  getAdminCustomFields:()=>req("/admin/custom-fields"),createCustomField:d=>req("/admin/custom-fields",{method:"POST",body:JSON.stringify(d)}),
  updateCustomField:(id,d)=>req(`/admin/custom-fields/${id}`,{method:"PUT",body:JSON.stringify(d)}),deleteCustomField:id=>req(`/admin/custom-fields/${id}`,{method:"DELETE"}),
  getUsers:()=>req("/auth/users"),updateUser:(id,d)=>req(`/auth/users/${id}`,{method:"PUT",body:JSON.stringify(d)}),deleteUser:id=>req(`/auth/users/${id}`,{method:"DELETE"}),
  getSnapshots:()=>req("/admin/snapshots"),createSnapshot:(n,d)=>req("/admin/snapshots",{method:"POST",body:JSON.stringify({name:n,description:d})}),
  restoreSnapshot:id=>req(`/admin/snapshots/${id}/restore`,{method:"POST"}),deleteSnapshot:id=>req(`/admin/snapshots/${id}`,{method:"DELETE"}),
  getSystemInfo:()=>req("/admin/system-info"),
};
